### ISSUE TITLE
KeyError: 'examples'

### ISSUE THREAD

**Issue by lemassykoi** [ycahome/pp-manager#45]
Hi,

everyday at 12.00 I got this error messages in Domoticz Log :

```
2023-02-13 12:00:54.111 Error: PyPM: Call to function 'onHeartbeat' failed, exception details:
2023-02-13 12:00:54.128 Error: PyPM: Traceback (most recent call last):
2023-02-13 12:00:54.128 Error: PyPM: File "/home/pi/domoticz/plugins/PP-MANAGER/plugin.py", line 788, in onHeartbeat
2023-02-13 12:00:54.128 Error: PyPM: _plugin.onHeartbeat()
2023-02-13 12:00:54.128 Error: PyPM: File "/home/pi/domoticz/plugins/PP-MANAGER/plugin.py", line 456, in onHeartbeat
2023-02-13 12:00:54.128 Error: PyPM: self.CheckForUpdatePythonPlugin(self.plugindata[Parameters["Mode2"]][0], self.plugindata[Parameters["Mode2"]][1], str(dir))
2023-02-13 12:00:54.128 Error: PyPM: File "/home/pi/domoticz/plugins/PP-MANAGER/plugin.py", line 580, in CheckForUpdatePythonPlugin
2023-02-13 12:00:54.128 Error: PyPM: if (self.plugindata[ppKey][2] in self.ExceptionList):
2023-02-13 12:00:54.128 Error: PyPM: KeyError: 'examples'
```

I did a git update yesterday, but today same error

any idea why ? thanks

**Comment by galadril** [comment]
@lemassykoi i guess this is not an issue anymore, or is it?

**Comment by lemassykoi** [comment]
sadly, yes it is :

![image](https://github.com/user-attachments/assets/55dc7658-2022-4764-94d8-70db1c0b388b)
